[package]
name = "mwe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decorator = { path = "./decorator" }
near-sdk = "4.1.1"
